### ISSUE TITLE
`tacgt_300AAC_EPR` missing configs

### ISSUE THREAD

**Issue by jonpas** [Theseus-Aegis/GTArmory#145]
**Arma 3 Version:** `2.12`
**Theseus Modpack Version:** `3.35.4`

**Description:**
Missing config values for `tacgt_300AAC_EPR` ammo.
```
11:23:50 [ACE] (advanced_ballistics) WARNING: Subsonic Ammo tacgt_300AAC_EPR (329.2 m/s) missing `ACE_muzzleVelocities` or `ACE_ammoTempMuzzleVelocityShifts` configs, attempting to use parent tacgt_300AAC_Ball (329.2m/s)
```

**Steps to reproduce:**
- Load game.
- Shoot `tacgt_300AAC_EPR`.
- Read RPT.

**Expected behavior:**
No RPT warning.

**Where did the issue occur?**
- Dedicated (Ethan's RPT)

**Log Files:**
- Isolated to keep privacy.

**Additional context:**
/

**Screenshots:**
/

**Comment by Mike-MF** [comment]
Not subsonic anymore, best fix.
