### ISSUE TITLE
Supplies - Fuel Canister not showing up in Zeus

### ISSUE THREAD

**Issue by JoramD0** [Theseus-Aegis/GTArmory#178]
**Arma 3 Version:** `2.14`
**Theseus Modpack Version:** `4.0.1`

**Description:**
Title.

**Steps to reproduce:**
- Enter Zeus
- Fail to find Theseus branded fuel canister

**Expected behavior:**
A Theseus branded fuel canister

**Where did the issue occur?**
- Dedicated

**Log Files:**
- N/A

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by Mike-MF** [comment]
Fixed in #179
