### ISSUE TITLE
RFB/SDAR corrections

### ISSUE THREAD

**Issue by netshark993** [Theseus-Aegis/GTArmory#22]
Correct the vanilla SDAR into the Keltec RFB that it is modeled after and re-calibered into the correct 7.62x51 round. 

https://armedassault.fandom.com/wiki/SDAR
Scroll down to the Trivia section for more info.

**Comment by TyroneMF** [comment]
Will do by
Creating a 7.62x51 variant, Replace Armory variants with that one and leave vanilla one untouched.
