### ISSUE TITLE
G3 is not as accurate as needed

### ISSUE THREAD

**Issue by netshark993** [Theseus-Aegis/GTArmory#27]
**Arma 3 Version:** `x.yy`
**Theseus Modpack Version:** `x.y.z`

**Description:**

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Log Files:**
- Link to ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Additional context:**

**Screenshots:**

**Comment by TyroneMF** [comment]
No information, closing.
